### PR TITLE
ci: test with Elixir 1.14

### PR DESCRIPTION
**Pull request by fhunleth**

### CODE REVIEW

**Comment by fhunleth** [comment]
@jjcarstens Is this the CircleCI configuration that you like the most of the variations we have? If so, I'll copy/paste it over other ones when I update projects.

**Comment by jjcarstens** [comment]
I really like just specifying new hexpm tags and that's it. If you are thinking about applying this everywhere, I think I'd like to take a minute to see if there is a better way to specify that a tag should run everything or just the basics (like another param of the matrix?). And also if this is to go everywhere, maybe it's easier to supply as an orb?

Barring a little thought for those 2 things, I'm 👍

**Review by jjcarstens — APPROVED** [review]

**Comment by fhunleth** [comment]
Could you add to this commit what you want? I'll hold off merging.

**Comment by fhunleth** [comment]
I suppose if I have a wish list on CI, it's that `mix test` gets run on everything. Then in parallel, there's a mix format/mix credo build, and then there's a dialyzer build. The goal is to get as much feedback as possible quickly and then let the dialyzer build do it's thing. 

I like the idea of using an orb so that the configs can be really small. The only things I seem to change are the elixir/erlang/alpine versions and what gets apk installed. Not a big deal if this is too much work. As you know, I use merge tools for much of my maintenance, so big files aren't a showstopper for me.

**Pull request merged**
